# print(dir(list))
a=[1,2,3]
print(type(a))
print(a[1])
a[1]=5
print(a)
print(a[0],type(a[2]))
a='hello'
print(a[1])
print(a[3])
print(a[4])
print(a[0])
print(a[-4])
'''append'''
a=[1,65,'hello',25.5]
a.append('hi')
print(a)
a.append(-56.59)
print(a)
x=['hello','hi','world']
print(x)
x.append('python')
print(x)
"""clear"""
x=[56,78,95]
print(x)
x.clear()
print(x)
a=["hello","hi"]
a.clear()
print(a)
'''copy'''
a=[26,'hello',50.5]
print(a)
x=a.copy()
print(x)
'''count'''
a=[26,'hello',50.5]
print(a.count(a))
print(a.count(26))
print(a.count('hello'))
print(a.count(50.5))
'''extend'''
a=[26,'hello',50.5]
b=[1,2,3]
a.extend(b)
print(a)
b.extend(a)
print(b)
a=[26,'hello',50.5]
b=[98,65,0]
c=['m','r']
a.extend(c)
b.extend(a)
c.extend(b)
print(a)
print(b)
print(c)
'''index'''
a=[26,'hello',50.5]
print(a.index(26))
print(a.index('hello'))
print(a.index(50.5))